name: Test Examples
on:
  pull_request: # Run on all PR changes
  push: # Run on all changes to main (includes PR merges)
    branches:
      - main

jobs:
  # Run the example scripts and ensure there are no errors
  run-examples:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Minimal permissions required for checkout
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[examples]"

      - name: Test examples
        env:
          MPLBACKEND: Agg # Use non-interactive backend for matplotlib
        run: |
          cd examples
          for example in *.py; do
            echo "Testing $example..."
            python "$example" || { echo "Example $example failed"; exit 1; }
            echo "Example $example passed"
          done
